const constants = {
    ADD_USER: "ADD_USER",
    MUTE_USER: "MUTE_USER",
    BAN_USER: "BAN_USER",
    ONLINE_USER: "ONLINE_USER",

    LOGIN_USER: "LOGIN_USER",
    LOGOUT_USER: "LOGOUT_USER",
    UPDATE_USER:"UPDATE_USER",

    ADD_MESSAGE: "ADD_MESSAGE",

    SORT_MESSAGE: "SORT_MESSAGE",
    SORTED_BY_DATE: "SORTED_BY_DATE",

    PAGINATION_MESSAGE: "PAGINATION_MESSAGE",
    PAGINATION_SKIP: "PAGINATION_SKIP",
    PAGINATION_LIMIT: "PAGINATION_LIMIT",

    ADD_ERROR: "ADD_ERROR",
    REMOVE_ERROR:"REMOVE_ERROR"
};

export default constants
