export const ADD_TO_CART = 'ADD_TO_CART';
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST';
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS';
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';


export const LOGIN_REQUEST: 'USERS_LOGIN_REQUEST';
export const LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS';
export const LOGIN_FAILURE: 'USERS_LOGIN_FAILURE';

export const LOGOUT: 'USERS_LOGOUT';

export const GETALL_REQUEST: 'USERS_GETALL_REQUEST';
export const GETALL_SUCCESS: 'USERS_GETALL_SUCCESS';
export const GETALL_FAILURE: 'USERS_GETALL_FAILURE';



